#!/usr/bin/env bash

EXTENSIONS=(
abusaidm.html-snippets
ahmadawais.shades-of-purple
alefragnani.Bookmarks
alefragnani.project-manager
apollographql.vscode-apollo
atlassian.atlascode
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
codezombiech.gitignore
CoenraadS.bracket-pair-colorizer
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
DotJoshJohnson.xml
eamodio.gitlens
eg2.vscode-npm-script
esbenp.prettier-vscode
felixfbecker.php-intellisense
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
hollowtree.vue-snippets
HookyQR.beautify
ionutvmi.path-autocomplete
kumar-harsh.graphql-for-vscode
mhutchie.git-graph
mikestead.dotenv
ModoNoob.vscode-hipster-theme
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-vscode.Go
ms-vscode.powershell
ms-vscode.vscode-typescript-next
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
octref.vetur
PKief.material-icon-theme
redhat.java
redhat.vscode-xml
redhat.vscode-yaml
ryu1kn.partial-diff
sysoev.language-stylus
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
wix.vscode-import-cost
Zignd.html-css-class-completion
)

error_handler () {
    if [[ $? -ne 0 ]]; then
        echo "Error downloading $1"
    else
        echo -e "Done\n"
    fi
}

download_extensions () {
    for ext in "${EXTENSIONS[@]}"; do
        code --install-extension "$ext";
        error_handler "$ext"
    done
}

download_extensions

exit $?